"use client";

import { useState } from "react";
import { 
  BookOpen, 
  FileText, 
  Sparkles, 
  Copy, 
  Check, 
  Download, 
  Layers, 
  Code,
  CheckCircle2,
  RefreshCw
} from "lucide-react";

export function CatalogView() {
  const [docType, setDocType] = useState<"api" | "adr" | "changelog">("api");
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  // Sample generated docs
  const [docContent, setDocContent] = useState<string>(`# API Reference & Module Catalog
Generated by RepoMind AI Engine for PR #42

## 1. Authentication Endpoints

### \`GET /auth/github\`
Initiates OAuth flow with GitHub App.
- **Parameters**: None
- **Response**: 302 Redirect to GitHub OAuth Authorize URL
- **Security**: State token generated with 300s TTL.

### \`POST /analyze\`
Primary risk assessment entry point for pull requests.
- **Request Body**:
  \`\`\`json
  {
    "pr_url": "https://github.com/owner/repo/pull/123",
    "diff": "optional unified diff string"
  }
  \`\`\`
- **Response Schema**: \`AnalyzeResponse\` (Risk Level, Blast Radius, Missing Tests)

---

## 2. AST Blast Radius Engine
- **Module**: \`backend.dependency_finder\`
- **Function**: \`find_dependents(symbols, repo_files, changed_paths)\`
- **Output**: Array of filepaths referencing modified symbols.
`);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      if (docType === "adr") {
        setDocContent(`# Architecture Decision Record (ADR 004)
## Title: Zero-Token Authentication via GitHub App & OAuth

### Status
Accepted

### Context
Asking engineers for Personal Access Tokens (PATs) introduces security vulnerabilities and token leakage risks.

### Decision
We upgraded PR Risk Radar to use GitHub App installation tokens (mints short-lived 1-hour RS256 JWT tokens) for public and webhook analysis, paired with standard GitHub OAuth session cookies for private repository access.

### Consequences
- **Positive**: No personal user credentials stored.
- **Positive**: Automated webhook event processing without human interaction.
- **Tradeoff**: Requires GitHub App setup in organization settings.`);
      } else if (docType === "changelog") {
        setDocContent(`# PR Release Notes & Migration Guide
### Version 0.2.0 (IBM Bob 2.0 Hackathon)

#### Features Added
- **AST Blast Radius Mapping**: Downstream consumer detection across repository files.
- **SQLite Database Persistence**: Full history caching at \`data/pr_radar.db\`.
- **Multi-Model LLM Reasoning**: IBM watsonx.ai Granite 3.0 + Groq LLaMA-3 + Gemini fallback.

#### Breaking Changes
- \`AnalyzeRequest\` no longer accepts \`github_token\` in request body; authentication now flows through secure HTTP-only session cookies.

#### Suggested Tests to Execute
- \`tests/test_oauth_flow.py::test_session_validation\`
- \`tests/test_diff_parser.py::test_ast_symbol_extraction\``);
      } else {
        setDocContent(`# API Reference & Module Catalog
Generated by RepoMind AI Engine for PR #42

## 1. Authentication Endpoints

### \`GET /auth/github\`
Initiates OAuth flow with GitHub App.
- **Parameters**: None
- **Response**: 302 Redirect to GitHub OAuth Authorize URL
- **Security**: State token generated with 300s TTL.

### \`POST /analyze\`
Primary risk assessment entry point for pull requests.
- **Request Body**:
  \`\`\`json
  {
    "pr_url": "https://github.com/owner/repo/pull/123",
    "diff": "optional unified diff string"
  }
  \`\`\`
- **Response Schema**: \`AnalyzeResponse\` (Risk Level, Blast Radius, Missing Tests)

---

## 2. AST Blast Radius Engine
- **Module**: \`backend.dependency_finder\`
- **Function**: \`find_dependents(symbols, repo_files, changed_paths)\`
- **Output**: Array of filepaths referencing modified symbols.
`);
      }
    }, 800);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(docContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full bg-[#0b0c10] text-zinc-300 select-none overflow-hidden font-sans">
      
      {/* Top Header */}
      <div className="h-12 border-b border-white/[0.08] px-4 flex items-center justify-between bg-[#12141c]/90 flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 text-zinc-200 font-semibold text-xs uppercase tracking-wider">
            <BookOpen className="w-4 h-4 text-emerald-400" />
            <span>AI Documentation & Change Catalog</span>
          </div>

          <span className="text-zinc-600">|</span>

          {/* Doc Type Selector */}
          <div className="flex items-center gap-1 bg-[#181a24] p-0.5 rounded-lg border border-white/[0.08]">
            <button
              onClick={() => setDocType("api")}
              className={`px-2.5 py-1 rounded-md text-xs font-mono transition-colors ${
                docType === "api"
                  ? "bg-emerald-500/20 text-emerald-300 font-semibold"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              API Reference
            </button>
            <button
              onClick={() => setDocType("adr")}
              className={`px-2.5 py-1 rounded-md text-xs font-mono transition-colors ${
                docType === "adr"
                  ? "bg-emerald-500/20 text-emerald-300 font-semibold"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              ADR Architecture
            </button>
            <button
              onClick={() => setDocType("changelog")}
              className={`px-2.5 py-1 rounded-md text-xs font-mono transition-colors ${
                docType === "changelog"
                  ? "bg-emerald-500/20 text-emerald-300 font-semibold"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              PR Release Notes
            </button>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="h-7 px-3 rounded-md bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium transition-colors cursor-pointer flex items-center gap-1.5"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? "animate-spin" : ""}`} />
            <span>{isGenerating ? "Synthesizing Docs..." : "Regenerate from Changes"}</span>
          </button>

          <button
            onClick={handleCopy}
            className="h-7 px-2.5 rounded-md border border-white/[0.08] hover:bg-white/[0.06] text-xs font-mono text-zinc-300 flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-zinc-400" />}
            <span>{copied ? "Copied" : "Copy"}</span>
          </button>
        </div>
      </div>

      {/* Editor & Preview Area */}
      <div className="flex-1 p-6 overflow-y-auto bg-[#08090d] scrollbar-thin">
        <div className="max-w-4xl mx-auto rounded-xl border border-white/[0.08] bg-[#12141c]/90 p-8 shadow-xl font-mono text-xs leading-relaxed select-text">
          <pre className="whitespace-pre-wrap text-zinc-200 font-mono">
            {docContent}
          </pre>
        </div>
      </div>
    </div>
  );
}
